# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - debthelper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        # จุดตายอยู่ตรงนี้: บอกให้มันวิ่งเข้าโฟลเดอร์ frontend ก่อนทำงาน และใช้ npx เพื่อแก้เรื่อง Permission
        run: |
          npm install
          npx vite build
        working-directory: ./frontend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # บอกให้เก็บไฟล์จากโฟลเดอร์ dist ที่อยู่ใน frontend ขึ้นไป
          path: ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_627B3BF04FF040168135ED5FA66FBAF3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_980F0CB13746458189BB89329145C58D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7042060DE3104C4CB79B8D59D9C64764 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'debthelper'
          slot-name: 'Production'
          package: .
